language: rust
dist: bionic

install:
  # libwebp-dev: for libwebp
- sudo apt-get install -y gcc libwebp-dev
- rustup component add rustfmt clippy
script:
- cargo build --all --verbose
- cargo test --all --verbose
- cargo fmt --all -- --check
