[package]
name = "libwebp"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]
edition = "2018"

[dependencies]
libwebp-sys = { path = "libwebp-sys", default-features = false }

[features]
default = []
demux = ["libwebp-sys/demux"]
mux = ["libwebp-sys/mux"]
"0.5" = ["libwebp-sys/0.5"]
"0.6" = ["libwebp-sys/0.6", "0.5"]
"1.1" = ["libwebp-sys/1.1", "0.6"]
static = ["libwebp-sys/static"]
extern-types = ["libwebp-sys/extern-types"]
__doc_cfg = ["libwebp-sys/__doc_cfg", "1.1", "demux", "mux"]

[workspace]
members = [
  "libwebp-sys",
  "libwebp-image",
]
