[package]
name = "libwebp-image"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]

[dependencies]
libwebp = { path = "..", default-features = false }
image = "0.22"

[features]
default = ["libwebp-0.5"]
"libwebp-0.5" = ["libwebp/0.5"]
